USE [master]
GO
/****** Object:  Database [MiniGramCashDB]    Script Date: 24/04/2022 01:08:12 PM ******/
CREATE DATABASE [MiniGramCashDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MiniGramCashDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\MiniGramCashDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MiniGramCashDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\MiniGramCashDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [MiniGramCashDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MiniGramCashDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MiniGramCashDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MiniGramCashDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MiniGramCashDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MiniGramCashDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MiniGramCashDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [MiniGramCashDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MiniGramCashDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MiniGramCashDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MiniGramCashDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MiniGramCashDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MiniGramCashDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MiniGramCashDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MiniGramCashDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MiniGramCashDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MiniGramCashDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [MiniGramCashDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MiniGramCashDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MiniGramCashDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MiniGramCashDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MiniGramCashDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MiniGramCashDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MiniGramCashDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MiniGramCashDB] SET RECOVERY FULL 
GO
ALTER DATABASE [MiniGramCashDB] SET  MULTI_USER 
GO
ALTER DATABASE [MiniGramCashDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MiniGramCashDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MiniGramCashDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MiniGramCashDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MiniGramCashDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MiniGramCashDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'MiniGramCashDB', N'ON'
GO
ALTER DATABASE [MiniGramCashDB] SET QUERY_STORE = OFF
GO
USE [MiniGramCashDB]
GO
/****** Object:  Table [dbo].[TBLITEMS]    Script Date: 24/04/2022 01:08:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBLITEMS](
	[IID] [int] IDENTITY(1,1) NOT NULL,
	[INAME] [nvarchar](100) NULL,
	[QTE] [int] NULL,
	[UNIT] [nvarchar](20) NULL,
	[ADD_DATE] [datetime] NULL,
	[ENABLED] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[IID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBLPRODUCTS]    Script Date: 24/04/2022 01:08:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBLPRODUCTS](
	[PID] [int] IDENTITY(1,1) NOT NULL,
	[PNAME] [nvarchar](100) NULL,
	[QTE] [int] NULL,
	[PRICE] [float] NULL,
	[ADD_DATE] [datetime] NULL,
	[ENABLED] [bit] NULL,
	[HasQuantity] [bit] NULL,
	[BARCODE] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBLRECEIPTS]    Script Date: 24/04/2022 01:08:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBLRECEIPTS](
	[RID] [int] IDENTITY(1,1) NOT NULL,
	[RITEM_NB] [int] NULL,
	[TOTAL_AMOUNTDollar] [float] NULL,
	[TOTAL_AMOUNTLBP] [int] NULL,
	[RDATE] [datetime] NULL,
	[RBARCODE] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBLRECEIPTS_DETAILS]    Script Date: 24/04/2022 01:08:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBLRECEIPTS_DETAILS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[RID] [int] NULL,
	[PID] [int] NULL,
	[QTE] [int] NULL,
	[PRICE_Dollar] [float] NULL,
	[PRICE_LBP] [int] NULL,
	[TOTAL_PRICEDollar] [float] NULL,
	[TOTAL_PRICELBP] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TBLITEMS] ADD  DEFAULT ((0)) FOR [QTE]
GO
ALTER TABLE [dbo].[TBLITEMS] ADD  DEFAULT ((1)) FOR [ENABLED]
GO
ALTER TABLE [dbo].[TBLPRODUCTS] ADD  DEFAULT ((0)) FOR [QTE]
GO
ALTER TABLE [dbo].[TBLPRODUCTS] ADD  DEFAULT ((0.0)) FOR [PRICE]
GO
ALTER TABLE [dbo].[TBLPRODUCTS] ADD  DEFAULT ((1)) FOR [ENABLED]
GO
ALTER TABLE [dbo].[TBLPRODUCTS] ADD  CONSTRAINT [DF_TBLPRODUCTS_HasQuantity]  DEFAULT ((0)) FOR [HasQuantity]
GO
ALTER TABLE [dbo].[TBLPRODUCTS] ADD  DEFAULT ((0)) FOR [BARCODE]
GO
ALTER TABLE [dbo].[TBLRECEIPTS] ADD  DEFAULT ((0)) FOR [RITEM_NB]
GO
ALTER TABLE [dbo].[TBLRECEIPTS] ADD  DEFAULT ((0.0)) FOR [TOTAL_AMOUNTDollar]
GO
ALTER TABLE [dbo].[TBLRECEIPTS] ADD  DEFAULT ((0)) FOR [TOTAL_AMOUNTLBP]
GO
ALTER TABLE [dbo].[TBLRECEIPTS] ADD  DEFAULT ('0') FOR [RBARCODE]
GO
ALTER TABLE [dbo].[TBLRECEIPTS_DETAILS] ADD  DEFAULT ((0)) FOR [QTE]
GO
ALTER TABLE [dbo].[TBLRECEIPTS_DETAILS] ADD  DEFAULT ((0.0)) FOR [PRICE_Dollar]
GO
ALTER TABLE [dbo].[TBLRECEIPTS_DETAILS] ADD  DEFAULT ((0)) FOR [PRICE_LBP]
GO
ALTER TABLE [dbo].[TBLRECEIPTS_DETAILS] ADD  DEFAULT ((0.0)) FOR [TOTAL_PRICEDollar]
GO
ALTER TABLE [dbo].[TBLRECEIPTS_DETAILS] ADD  DEFAULT ((0)) FOR [TOTAL_PRICELBP]
GO
ALTER TABLE [dbo].[TBLRECEIPTS_DETAILS]  WITH CHECK ADD FOREIGN KEY([PID])
REFERENCES [dbo].[TBLPRODUCTS] ([PID])
GO
ALTER TABLE [dbo].[TBLRECEIPTS_DETAILS]  WITH CHECK ADD FOREIGN KEY([RID])
REFERENCES [dbo].[TBLRECEIPTS] ([RID])
GO
/****** Object:  StoredProcedure [dbo].[sp_addNewItem]    Script Date: 24/04/2022 01:08:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_addNewItem](@name nvarchar(100),@qte int,@unit NVARCHAR(20))
AS
BEGIN
INSERT INTO TBLITEMS(INAME,QTE,UNIT,ADD_DATE,ENABLED)VALUES(@name,@qte,@unit,GETDATE(),1)
END
GO
/****** Object:  StoredProcedure [dbo].[sp_addNewProduct]    Script Date: 24/04/2022 01:08:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_addNewProduct](@name nvarchar(100),@barcode nvarchar(100),@qte int,@price float,@hasQuantity BIT)
AS
BEGIN
INSERT INTO TBLPRODUCTS(PNAME,BARCODE,QTE,PRICE,ADD_DATE,ENABLED,HasQuantity)VALUES(@name,@barcode,@qte,@price,GETDATE(),1,@hasQuantity)
END
GO
/****** Object:  StoredProcedure [dbo].[sp_deleteReceiptByBarcode]    Script Date: 24/04/2022 01:08:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_deleteReceiptByBarcode](@barcode nvarchar(max))
AS
BEGIN
DELETE FROM TBLRECEIPTS WHERE RBARCODE = @barcode
END
GO
/****** Object:  StoredProcedure [dbo].[sp_deleteReceiptDetailsByRID]    Script Date: 24/04/2022 01:08:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_deleteReceiptDetailsByRID](@id int)
AS
BEGIN
DELETE FROM TBLRECEIPTS_DETAILS WHERE RID = @id
END
GO
/****** Object:  StoredProcedure [dbo].[sp_disableItemByID]    Script Date: 24/04/2022 01:08:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_disableItemByID](@id int)
AS
BEGIN
UPDATE TBLITEMS SET Enabled = 0 WHERE IID = @id
END
GO
/****** Object:  StoredProcedure [dbo].[sp_disableProductByID]    Script Date: 24/04/2022 01:08:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_disableProductByID](@id int)
AS
BEGIN
UPDATE TBLPRODUCTS SET Enabled = 0 WHERE PID = @id
END
GO
/****** Object:  StoredProcedure [dbo].[sp_enableItemByID]    Script Date: 24/04/2022 01:08:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_enableItemByID](@id int)
AS
BEGIN
UPDATE TBLITEMS SET Enabled = 1 WHERE IID = @id
END
GO
/****** Object:  StoredProcedure [dbo].[sp_enableProductByID]    Script Date: 24/04/2022 01:08:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_enableProductByID](@id int)
AS
BEGIN
UPDATE TBLPRODUCTS SET Enabled = 1 WHERE PID = @id
END
GO
/****** Object:  StoredProcedure [dbo].[sp_getLastReceiptID]    Script Date: 24/04/2022 01:08:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_getLastReceiptID]
AS
BEGIN
SELECT MAX(RID) AS MAX_RID FROM TBLRECEIPTS
END
GO
/****** Object:  StoredProcedure [dbo].[sp_getProductByName]    Script Date: 24/04/2022 01:08:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_getProductByName](@name nvarchar(max))
AS
BEGIN
SELECT * FROM TBLPRODUCTS WHERE PNAME = @name OR BARCODE = @name
END
GO
/****** Object:  StoredProcedure [dbo].[sp_getProductsCount]    Script Date: 24/04/2022 01:08:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_getProductsCount](@str NVARCHAR(MAX))
AS
BEGIN
IF(@str = '')
	SELECT COUNT(PID) AS Product_Number FROM TBLPRODUCTS Where Enabled = 1
ELSE
BEGIN
	DECLARE @isDigit BIT
	SELECt @isDigit = ISNUMERIC(@str)
	IF(@isDigit = 1)
		SELECT COUNT(PID) AS Product_Number FROM TBLPRODUCTS Where Enabled = 1 AND (PID LIKE '%'+@str+'%' OR BARCODE LIKE '%'+@str+'%')
	ELSE
		SELECT COUNT(PID) AS Product_Number FROM TBLPRODUCTS Where Enabled = 1 AND PNAME LIKE '%'+@str+'%'
END
END
GO
/****** Object:  StoredProcedure [dbo].[sp_getReceiptByBarcode]    Script Date: 24/04/2022 01:08:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_getReceiptByBarcode](@barcode nvarchar(max))
AS
BEGIN
SELECT * FROM TBLRECEIPTS WHERE RBARCODE = @barcode
END
GO
/****** Object:  StoredProcedure [dbo].[sp_getReceiptByID]    Script Date: 24/04/2022 01:08:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_getReceiptByID](@id int)
AS
BEGIN
SELECT * FROM TBLRECEIPTS WHERE RID =@id
END
GO
/****** Object:  StoredProcedure [dbo].[sp_insertNewRecipt]    Script Date: 24/04/2022 01:08:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_insertNewRecipt](@barcode nvarchar(max),@itemnb int,@totaldollar float,@totallbp int)
AS
BEGIN
INSERT INTO TBLRECEIPTS(RBARCODE,RITEM_NB,TOTAL_AMOUNTDollar,TOTAL_AMOUNTLBP,RDATE)VALUES(@barcode,@itemnb,@totaldollar,@totallbp,GETDATE())
END
GO
/****** Object:  StoredProcedure [dbo].[sp_insertNewReciptDetail]    Script Date: 24/04/2022 01:08:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_insertNewReciptDetail](@rid int,@pid int,@qte int,@pricedollar float,@totaldollar float,@pricelbp int,@totallbp int)
AS
BEGIN
INSERT INTO TBLRECEIPTS_DETAILS(RID,PID,QTE,PRICE_Dollar,PRICE_LBP,TOTAL_PRICEDollar,TOTAL_PRICELBP)VALUES(@rid,@pid,@qte,@pricedollar,@pricelbp,@totaldollar,@totallbp)
END
GO
/****** Object:  StoredProcedure [dbo].[sp_select_item]    Script Date: 24/04/2022 01:08:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_select_item](@str NVARCHAR(MAX))
AS 
BEGIN
IF(@str = '')
	SELECT IID AS ID,INAME AS ItemName,QTE AS Quantity,Unit,ADD_DATE AS AddedDate, CASE WHEN ENABLED = 1 THEN 'Enabled' ELSE 'Disabled' END AS Status FROM TBLITEMS ORDER BY IID ASC
ELSE
BEGIN
	DECLARE @isDigit BIT
	SELECt @isDigit = ISNUMERIC(@str)
	IF(@isDigit = 1)
		SELECT IID AS ID,INAME AS ItemName,QTE AS Quantity,Unit,ADD_DATE AS AddedDate, CASE WHEN ENABLED = 1 THEN 'Enabled' ELSE 'Disabled' END AS Status FROM TBLITEMS WHERE IID LIKE '%'+@str+'%' ORDER BY IID ASC
	ELSE
		SELECT IID AS ID,INAME AS ItemName,QTE AS Quantity,Unit,ADD_DATE AS AddedDate, CASE WHEN ENABLED = 1 THEN 'Enabled' ELSE 'Disabled' END AS Status FROM TBLITEMS WHERE INAME LIKE '%'+@str+'%' ORDER BY IID ASC
END
END
GO
/****** Object:  StoredProcedure [dbo].[sp_select_products]    Script Date: 24/04/2022 01:08:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_select_products](@str NVARCHAR(MAX))
AS 
BEGIN
IF(@str = '')
	SELECT PID AS ID,BARCODE AS Barcode,PNAME AS ProductName,QTE AS Quantity,PRICE AS Price,ADD_DATE AS AddedDate, CASE WHEN ENABLED = 1 THEN 'Enabled' ELSE 'Disabled' END AS Status FROM TBLPRODUCTS ORDER BY PID ASC
ELSE
BEGIN
	DECLARE @isDigit BIT
	SELECt @isDigit = ISNUMERIC(@str)
	IF(@isDigit = 1)
		SELECT PID AS ID,BARCODE AS Barcode,PNAME AS ProductName,QTE AS Quantity,PRICE AS Price,ADD_DATE AS AddedDate, CASE WHEN ENABLED = 1 THEN 'Enabled' ELSE 'Disabled' END AS Status FROM TBLPRODUCTS WHERE PID LIKE '%'+@str+'%' OR BARCODE LIKE '%'+@str+'%' ORDER BY PID ASC
	ELSE
		SELECT PID AS ID,BARCODE AS Barcode,PNAME AS ProductName,QTE AS Quantity,PRICE AS Price,ADD_DATE AS AddedDate, CASE WHEN ENABLED = 1 THEN 'Enabled' ELSE 'Disabled' END AS Status FROM TBLPRODUCTS WHERE PNAME LIKE '%'+@str+'%' ORDER BY PID ASC
END
END
GO
/****** Object:  StoredProcedure [dbo].[sp_selectReceipts]    Script Date: 24/04/2022 01:08:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_selectReceipts](@str nvarchar(max))
AS
BEGIN
SELECT RID AS ID,RBARCODE AS BARCODE, RITEM_NB AS NumberOfItem,TOTAL_AMOUNTDollar AS TotalDolarPrice,TOTAL_AMOUNTLBP AS TotalLBPPrice,RDATE AS Date FROM TBLRECEIPTS WHERE RID LIKE '%'+@str+'%' OR RBARCODE LIKE '%'+@str+'%' order by RID DESC
END
GO
/****** Object:  StoredProcedure [dbo].[sp_selectReceiptsDetails]    Script Date: 24/04/2022 01:08:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_selectReceiptsDetails](@id int)
AS
BEGIN
SELECT r.RBARCODE AS Barcode,rd.RID AS RID,p.PNAME AS ProductName,rd.QTE AS Quantity,rd.PRICE_Dollar AS DollarPrice,rd.PRICE_LBP AS LBPPrice,
	rd.TOTAL_PRICEDollar AS TotalDolarPrice,rd.TOTAL_PRICELBP AS TotalLBPPrice FROM TBLRECEIPTS r INNER JOIN TBLRECEIPTS_DETAILS rd ON r.RID = rd.RID
	INNER JOIN TBLPRODUCTS p ON rd.PID = p.PID  WHERE r.RID = @id ORDER BY r.RID ASC
END
GO
/****** Object:  StoredProcedure [dbo].[sp_UpdateItem]    Script Date: 24/04/2022 01:08:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_UpdateItem](@id int,@name nvarchar(100),@qte int,@unit nvarchar(20))
AS
BEGIN
UPDATE TBLITEMS SET INAME = @name WHERE IID = @id
UPDATE TBLITEMS SET QTE = @qte WHERE IID = @id
UPDATE TBLITEMS SET UNIT = @unit WHERE IID = @id
END
GO
/****** Object:  StoredProcedure [dbo].[sp_UpdateProduct]    Script Date: 24/04/2022 01:08:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_UpdateProduct](@id int,@name nvarchar(100),@barcode nvarchar(100),@qte int,@price float,@hasQuantity BIT)
AS
BEGIN
UPDATE TBLPRODUCTS SET PNAME = @name WHERE PID = @id
UPDATE TBLPRODUCTS SET BARCODE = @barcode WHERE PID = @id
UPDATE TBLPRODUCTS SET QTE = @qte WHERE PID = @id
UPDATE TBLPRODUCTS SET PRICE = @price WHERE PID = @id
UPDATE TBLPRODUCTS SET HasQuantity = @hasQuantity WHERE PID = @id
END
GO
/****** Object:  StoredProcedure [dbo].[sp_UpdateProductQuantity]    Script Date: 24/04/2022 01:08:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/****** Script for SelectTopNRows command from SSMS  ******/
CREATE PROCEDURE [dbo].[sp_UpdateProductQuantity](@id int,@qte int)
AS
BEGIN
UPDATE TBLPRODUCTS SET QTE = @qte WHERE PID = @id
END
GO
USE [master]
GO
ALTER DATABASE [MiniGramCashDB] SET  READ_WRITE 
GO
