
IF NOT EXISTS (SELECT NAME FROM master.dbo.sysdatabases WHERE NAME = 'MiniGramCashDB')
	CREATE DATABASE MiniGramCashDB
GO
USE [MiniGramCashDB]
CREATE TABLE TBLPRODUCTS(PID INT IDENTITY(1,1) PRIMARY KEY,PNAME NVARCHAR(100),QTE INT DEFAULT 0,PRICE FLOAT DEFAULT 0.0,ADD_DATE DATETIME,ENABLED BIT DEFAULT 1)
GO
CREATE TABLE TBLITEMS(IID INT IDENTITY(1,1) PRIMARY KEY,INAME NVARCHAR(100),QTE INT DEFAULT 0,UNIT NVARCHAR(20),ADD_DATE DATETIME,ENABLED BIT DEFAULT 1)
GO
CREATE TABLE  TBLRECEIPTS(RID INT IDENTITY(1,1) PRIMARY KEY,RITEM_NB INT DEFAULT 0,TOTAL_AMOUNT FLOAT DEFAULT 0.0,RDATE DATETIME)
CREATE TABLE TBLRECEIPTS_DETAILS(ID INT IDENTITY(1,1) PRIMARY KEY,RID INT FOREIGN KEY REFERENCES TBLRECEIPTS(RID),PID INT FOREIGN KEY REFERENCES TBLPRODUCTS(PID),QTE INT DEFAULT 0,PRICE FLOAT DEFAULT 0.0,TOTAL_PRICE FLOAT DEFAULT 0.0)