<?xml version="1.0" encoding="utf-8"?><Database Name="MiniGramCashDB" Class="MiniGramDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=AYkudo-PC;Initial Catalog=MiniGramCashDB;Integrated Security=True" SettingsObjectName="MiniGram.Properties.Settings" SettingsPropertyName="MiniGramCashDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TBLEXPIREDDATES" Member="TBLEXPIREDDATEs">
    <Type Name="TBLEXPIREDDATE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Qte" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExpiredDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="dateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="TBLPRODUCT_TBLEXPIREDDATE" Member="TBLPRODUCT" ThisKey="PID" OtherKey="PID" Type="TBLPRODUCT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLITEMS" Member="TBLITEMs">
    <Type Name="TBLITEM">
      <Column Name="IID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="INAME" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="QTE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UNIT" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ADD_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ENABLED" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLSUPPLIERS" Member="TBLSUPPLIERs">
    <Type Name="TBLSUPPLIER">
      <Column Name="SID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SNAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SPHONE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SEMAIL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ADD_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ENABLED" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TBLSUPPLIER_TBLPRODUCT" Member="TBLPRODUCTs" ThisKey="SID" OtherKey="SID" Type="TBLPRODUCT" />
      <Association Name="TBLSUPPLIER_TBLPRODUCT1" Member="TBLPRODUCTs1" ThisKey="SID" OtherKey="SID" Type="TBLPRODUCT" />
    </Type>
  </Table>
  <Table Name="dbo.TBLRECEIPTTYPES" Member="TBLRECEIPTTYPEs">
    <Type Name="TBLRECEIPTTYPE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TypeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLPRODUCTS" Member="TBLPRODUCTs">
    <Type Name="TBLPRODUCT">
      <Column Name="PID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PNAME" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="QTE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PRICE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ADD_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ENABLED" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HasQuantity" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BARCODE" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HasExpiredDate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HasTVA" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="InitPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SecondaryPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiscountPercentage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HasDiscount" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TBLPRODUCT_TBLEXPIREDDATE" Member="TBLEXPIREDDATEs" ThisKey="PID" OtherKey="PID" Type="TBLEXPIREDDATE" />
      <Association Name="TBLPRODUCT_TBLRECEIPTS_DETAIL" Member="TBLRECEIPTS_DETAILs" ThisKey="PID" OtherKey="PID" Type="TBLRECEIPTS_DETAIL" />
      <Association Name="TBLPRODUCT_TBLRECEIPTS_DETAIL1" Member="TBLRECEIPTS_DETAILs1" ThisKey="PID" OtherKey="PID" Type="TBLRECEIPTS_DETAIL" />
      <Association Name="TBLPRODUCT_TBLHOLDDETAIL" Member="TBLHOLDDETAILs" ThisKey="PID" OtherKey="PID" Type="TBLHOLDDETAIL" />
      <Association Name="TBLSUPPLIER_TBLPRODUCT" Member="TBLSUPPLIER" ThisKey="SID" OtherKey="SID" Type="TBLSUPPLIER" IsForeignKey="true" />
      <Association Name="TBLSUPPLIER_TBLPRODUCT1" Member="TBLSUPPLIER1" ThisKey="SID" OtherKey="SID" Type="TBLSUPPLIER" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLDELIVERY_RECEIPTS" Member="TBLDELIVERY_RECEIPTs">
    <Type Name="TBLDELIVERY_RECEIPT">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReceiptBarcode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RefID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ReceiptTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SupplierID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReceiptDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TotalQuantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalDiscount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalLBP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalDollar" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalTVA" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLDELIVERY_RECEIPTS_DETAILS" Member="TBLDELIVERY_RECEIPTS_DETAILs">
    <Type Name="TBLDELIVERY_RECEIPTS_DETAIL">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SellPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SecondaryPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Discount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cost" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="HasTVA" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HasDiscount" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HasExpDate" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ExpDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLVERSIONS" Member="TBLVERSIONs">
    <Type Name="TBLVERSION">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CurrentVersion" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="LastUpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLCUSTOMERS" Member="TBLCUSTOMERs">
    <Type Name="TBLCUSTOMER">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="isVIP" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="dateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLCUSTOMERS_ADDRESSES" Member="TBLCUSTOMERS_ADDRESSes">
    <Type Name="TBLCUSTOMERS_ADDRESS">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddressDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLRECEIPTS_DETAILS" Member="TBLRECEIPTS_DETAILs">
    <Type Name="TBLRECEIPTS_DETAIL">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QTE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PRICE_Dollar" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PRICE_LBP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TOTAL_PRICEDollar" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TOTAL_PRICELBP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalTVA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalDiscount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Profit" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="TBLPRODUCT_TBLRECEIPTS_DETAIL" Member="TBLPRODUCT" ThisKey="PID" OtherKey="PID" Type="TBLPRODUCT" IsForeignKey="true" />
      <Association Name="TBLPRODUCT_TBLRECEIPTS_DETAIL1" Member="TBLPRODUCT1" ThisKey="PID" OtherKey="PID" Type="TBLPRODUCT" IsForeignKey="true" />
      <Association Name="TBLRECEIPT_TBLRECEIPTS_DETAIL" Member="TBLRECEIPT" ThisKey="RID" OtherKey="RID" Type="TBLRECEIPT" IsForeignKey="true" />
      <Association Name="TBLRECEIPT_TBLRECEIPTS_DETAIL1" Member="TBLRECEIPT1" ThisKey="RID" OtherKey="RID" Type="TBLRECEIPT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLRECEIPTS" Member="TBLRECEIPTs">
    <Type Name="TBLRECEIPT">
      <Column Name="RID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReceiptTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RITEM_NB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TOTAL_AMOUNTDollar" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TOTAL_AMOUNTLBP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalTVA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalDiscount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="RDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RBARCODE" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="isHold" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EmpCardNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="restDollar" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="restLBP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="customerDollar" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="customerLBP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalProfit" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="TBLRECEIPT_TBLRECEIPTS_DETAIL" Member="TBLRECEIPTS_DETAILs" ThisKey="RID" OtherKey="RID" Type="TBLRECEIPTS_DETAIL" />
      <Association Name="TBLRECEIPT_TBLRECEIPTS_DETAIL1" Member="TBLRECEIPTS_DETAILs1" ThisKey="RID" OtherKey="RID" Type="TBLRECEIPTS_DETAIL" />
      <Association Name="TBLRECEIPT_TBLHOLDDETAIL" Member="TBLHOLDDETAILs" ThisKey="RID" OtherKey="RID" Type="TBLHOLDDETAIL" />
    </Type>
  </Table>
  <Table Name="dbo.TBLHOLDDETAILS" Member="TBLHOLDDETAILs">
    <Type Name="TBLHOLDDETAIL">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QTE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PRICE_Dollar" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PRICE_LBP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TOTAL_PRICEDollar" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TOTAL_PRICELBP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalTVA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalDiscount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Profit" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="TBLRECEIPT_TBLHOLDDETAIL" Member="TBLRECEIPT" ThisKey="RID" OtherKey="RID" Type="TBLRECEIPT" IsForeignKey="true" />
      <Association Name="TBLPRODUCT_TBLHOLDDETAIL" Member="TBLPRODUCT" ThisKey="PID" OtherKey="PID" Type="TBLPRODUCT" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_addNewItem" Method="sp_addNewItem">
    <Parameter Name="name" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="qte" Type="System.Int32" DbType="Int" />
    <Parameter Name="unit" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_disableItemByID" Method="sp_disableItemByID">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_disableProductByID" Method="sp_disableProductByID">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_enableItemByID" Method="sp_enableItemByID">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_enableProductByID" Method="sp_enableProductByID">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_getLastReceiptID" Method="sp_getLastReceiptID">
    <ElementType Name="sp_getLastReceiptIDResult">
      <Column Name="MAX_RID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_select_item" Method="sp_select_item">
    <Parameter Name="str" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="sp_select_itemResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="AddedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_UpdateItem" Method="sp_UpdateItem">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="name" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="qte" Type="System.Int32" DbType="Int" />
    <Parameter Name="unit" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_deleteReceiptByBarcode" Method="sp_deleteReceiptByBarcode">
    <Parameter Name="barcode" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_deleteReceiptDetailsByRID" Method="sp_deleteReceiptDetailsByRID">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UpdateProductQuantity" Method="sp_UpdateProductQuantity">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="qte" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_select_suppliers" Method="sp_select_suppliers">
    <Parameter Name="str" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="sp_select_suppliersResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SupplierName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AddedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_UpdateSupplier" Method="sp_UpdateSupplier">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="phone" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="email" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_enableSupplierByID" Method="sp_enableSupplierByID">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_disableSupplierByID" Method="sp_disableSupplierByID">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_addNewSupplier" Method="sp_addNewSupplier">
    <Parameter Name="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="phone" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="email" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_getSIDBySNAME" Method="sp_getSIDBySNAME">
    <Parameter Name="name" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="sp_getSIDBySNAMEResult">
      <Column Name="SID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_getSupplierByID" Method="sp_getSupplierByID">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_getSupplierByIDResult">
      <Column Name="SID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SNAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SPHONE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SEMAIL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ADD_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ENABLED" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_getSupplierByNAME" Method="sp_getSupplierByNAME">
    <Parameter Name="name" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="sp_getSupplierByNAMEResult">
      <Column Name="SID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SNAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SPHONE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SEMAIL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ADD_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ENABLED" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_getTotalOfExpiredDateQteByPID" Method="sp_getTotalOfExpiredDateQteByPID">
    <Parameter Name="pid" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_getTotalOfExpiredDateQteByPIDResult">
      <Column Name="TotalQte" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_getTotalOfExpiredDateQteByPName" Method="sp_getTotalOfExpiredDateQteByPName">
    <Parameter Name="pname" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="sp_getTotalOfExpiredDateQteByPNameResult">
      <Column Name="TotalQte" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_UpdateExpiredDateQte" Method="sp_UpdateExpiredDateQte">
    <Parameter Name="expID" Type="System.Int32" DbType="Int" />
    <Parameter Name="qte" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_deleteHoldReceiptDetailsByRID" Method="sp_deleteHoldReceiptDetailsByRID">
    <Parameter Name="rid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_getBestItems" Method="sp_getBestItems">
    <Parameter Name="date" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="sp_getBestItemsResult">
      <Column Name="PNAME" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TOTAL" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_getBestSuppliers" Method="sp_getBestSuppliers">
    <Parameter Name="date" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="sp_getBestSuppliersResult">
      <Column Name="SNAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TOTAL" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_getAllExpiredDateProducts" Method="sp_getAllExpiredDateProducts">
    <ElementType Name="sp_getAllExpiredDateProductsResult">
      <Column Name="BARCODE" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PNAME" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SNAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Qte" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExpiredDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_getSalesProductCountByDate" Method="sp_getSalesProductCountByDate">
    <Parameter Name="fromDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="toDate" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="sp_getSalesProductCountByDateResult">
      <Column Name="BARCODE" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PNAME" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NUM" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_insertNewReciptDetail" Method="sp_insertNewReciptDetail">
    <Parameter Name="rid" Type="System.Int32" DbType="Int" />
    <Parameter Name="pid" Type="System.Int32" DbType="Int" />
    <Parameter Name="qte" Type="System.Int32" DbType="Int" />
    <Parameter Name="pricedollar" Type="System.Double" DbType="Float" />
    <Parameter Name="totaldollar" Type="System.Double" DbType="Float" />
    <Parameter Name="pricelbp" Type="System.Int32" DbType="Int" />
    <Parameter Name="totallbp" Type="System.Int32" DbType="Int" />
    <Parameter Name="totaltva" Type="System.Double" DbType="Float" />
    <Parameter Name="totaldiscount" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_selectReceipts" Method="sp_selectReceipts">
    <Parameter Name="str" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="sp_selectReceiptsResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReceiptTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BARCODE" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="NumberOfItem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalDolarPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalLBPPrice" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalTVAPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalDiscount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="isHold" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EmpCardNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_insertNewRecipt" Method="sp_insertNewRecipt">
    <Parameter Name="barcode" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="itemnb" Type="System.Int32" DbType="Int" />
    <Parameter Name="totaldollar" Type="System.Double" DbType="Float" />
    <Parameter Name="totallbp" Type="System.Int32" DbType="Int" />
    <Parameter Name="totaltva" Type="System.Double" DbType="Float" />
    <Parameter Name="totaldiscount" Type="System.Double" DbType="Float" />
    <Parameter Name="receiptTypeID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_getReceiptByID" Method="sp_getReceiptByID">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_getReceiptByIDResult">
      <Column Name="RID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReceiptTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RITEM_NB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TOTAL_AMOUNTDollar" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TOTAL_AMOUNTLBP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalTVA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalDiscount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="RDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RBARCODE" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="isHold" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EmpCardNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_getReceiptByBarcode" Method="sp_getReceiptByBarcode">
    <Parameter Name="barcode" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="sp_getReceiptByBarcodeResult">
      <Column Name="RID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReceiptTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RITEM_NB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TOTAL_AMOUNTDollar" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TOTAL_AMOUNTLBP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalTVA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalDiscount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="RDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RBARCODE" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="isHold" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EmpCardNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_addNewProduct" Method="sp_addNewProduct">
    <Parameter Name="name" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="barcode" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="qte" Type="System.Int32" DbType="Int" />
    <Parameter Name="price" Type="System.Double" DbType="Float" />
    <Parameter Name="hasQuantity" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="sid" Type="System.Int32" DbType="Int" />
    <Parameter Name="hasExpiredDate" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="hasTVA" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="initprice" Type="System.Double" DbType="Float" />
    <Parameter Name="secondPrice" Type="System.Double" DbType="Float" />
    <Parameter Name="discountPercentage" Type="System.Int32" DbType="Int" />
    <Parameter Name="hasDiscount" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_getProductByName" Method="sp_getProductByName">
    <Parameter Name="name" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="sp_getProductByNameResult">
      <Column Name="PID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PNAME" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="QTE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PRICE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ADD_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ENABLED" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HasQuantity" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BARCODE" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HasExpiredDate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HasTVA" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="InitPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SecondaryPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiscountPercentage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HasDiscount" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_UpdateProduct" Method="sp_UpdateProduct">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="name" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="barcode" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="qte" Type="System.Int32" DbType="Int" />
    <Parameter Name="price" Type="System.Double" DbType="Float" />
    <Parameter Name="hasQuantity" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="sid" Type="System.Int32" DbType="Int" />
    <Parameter Name="hasExpiredDate" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="hasTVA" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="initprice" Type="System.Double" DbType="Float" />
    <Parameter Name="secondprice" Type="System.Double" DbType="Float" />
    <Parameter Name="discountPercentage" Type="System.Int32" DbType="Int" />
    <Parameter Name="hasDiscount" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_select_products" Method="sp_select_products">
    <Parameter Name="str" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="sp_select_productsResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Barcode" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SupplierName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AddedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="InitPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SecondaryPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="HasTVA" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DiscountPercentage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HasDiscount" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_getProductsCount" Method="sp_getProductsCount">
    <Parameter Name="str" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="sp_getProductsCountResult">
      <Column Name="Product_Number" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_selectDeliveryReceipts" Method="sp_selectDeliveryReceipts">
    <Parameter Name="str" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="sp_selectDeliveryReceiptsResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReceiptTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BARCODE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NumberOfItem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalDolarPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalLBPPrice" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalTVAPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalDiscount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_getProductList" Method="sp_getProductList">
    <ElementType Name="sp_getProductListResult">
      <Column Name="BARCODE" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PNAME" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SNAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PRICE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="QTE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HasQuantity" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HasExpiredDate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HasTVA" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="InitPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SecondaryPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiscountPercentage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HasDiscount" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_enableCustomerByID" Method="sp_enableCustomerByID">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_disableCustomerByID" Method="sp_disableCustomerByID">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_selectAllCustomers" Method="sp_selectAllCustomers">
    <Parameter Name="str" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="sp_selectAllCustomersResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="isVIP" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Enabled" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="dateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_getDailyCashByDate" Method="sp_getDailyCashByDate">
    <Parameter Name="fromDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="toDate" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="sp_getDailyCashByDateResult">
      <Column Name="RBARCODE" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="RITEM_NB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TOTAL_AMOUNTDollar" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TOTAL_AMOUNTLBP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TotalTVA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalDiscount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalProfit" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_selectDeliveryReceiptsDetails" Method="sp_selectDeliveryReceiptsDetails">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_selectDeliveryReceiptsDetailsResult">
      <Column Name="Barcode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RefID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SupplierName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SellPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SecondaryPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Discount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cost" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalQuantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalDiscount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalLBP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalDollar" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalTVA" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_selectReceiptsDetails" Method="sp_selectReceiptsDetails">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_selectReceiptsDetailsResult">
      <Column Name="Barcode" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="RID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SupplierName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DollarPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LBPPrice" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalDolarPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalLBPPrice" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalTVA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalDiscount" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>