#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniGram.LINQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MiniGramCashDB")]
	public partial class MiniGramDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBLITEM(TBLITEM instance);
    partial void UpdateTBLITEM(TBLITEM instance);
    partial void DeleteTBLITEM(TBLITEM instance);
    partial void InsertTBLRECEIPTS_DETAIL(TBLRECEIPTS_DETAIL instance);
    partial void UpdateTBLRECEIPTS_DETAIL(TBLRECEIPTS_DETAIL instance);
    partial void DeleteTBLRECEIPTS_DETAIL(TBLRECEIPTS_DETAIL instance);
    partial void InsertTBLRECEIPT(TBLRECEIPT instance);
    partial void UpdateTBLRECEIPT(TBLRECEIPT instance);
    partial void DeleteTBLRECEIPT(TBLRECEIPT instance);
    partial void InsertTBLSUPPLIER(TBLSUPPLIER instance);
    partial void UpdateTBLSUPPLIER(TBLSUPPLIER instance);
    partial void DeleteTBLSUPPLIER(TBLSUPPLIER instance);
    partial void InsertTBLPRODUCT(TBLPRODUCT instance);
    partial void UpdateTBLPRODUCT(TBLPRODUCT instance);
    partial void DeleteTBLPRODUCT(TBLPRODUCT instance);
    #endregion
		
		public MiniGramDBDataContext() : 
				base(global::MiniGram.Properties.Settings.Default.MiniGramCashDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MiniGramDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MiniGramDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MiniGramDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MiniGramDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBLITEM> TBLITEMs
		{
			get
			{
				return this.GetTable<TBLITEM>();
			}
		}
		
		public System.Data.Linq.Table<TBLRECEIPTS_DETAIL> TBLRECEIPTS_DETAILs
		{
			get
			{
				return this.GetTable<TBLRECEIPTS_DETAIL>();
			}
		}
		
		public System.Data.Linq.Table<TBLRECEIPT> TBLRECEIPTs
		{
			get
			{
				return this.GetTable<TBLRECEIPT>();
			}
		}
		
		public System.Data.Linq.Table<TBLSUPPLIER> TBLSUPPLIERs
		{
			get
			{
				return this.GetTable<TBLSUPPLIER>();
			}
		}
		
		public System.Data.Linq.Table<TBLPRODUCT> TBLPRODUCTs
		{
			get
			{
				return this.GetTable<TBLPRODUCT>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_addNewItem")]
		public int sp_addNewItem([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> qte, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string unit)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, qte, unit);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_disableItemByID")]
		public int sp_disableItemByID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_disableProductByID")]
		public int sp_disableProductByID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_enableItemByID")]
		public int sp_enableItemByID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_enableProductByID")]
		public int sp_enableProductByID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_getLastReceiptID")]
		public ISingleResult<sp_getLastReceiptIDResult> sp_getLastReceiptID()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_getLastReceiptIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_getProductsCount")]
		public ISingleResult<sp_getProductsCountResult> sp_getProductsCount([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string str)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), str);
			return ((ISingleResult<sp_getProductsCountResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_getReceiptByBarcode")]
		public ISingleResult<sp_getReceiptByBarcodeResult> sp_getReceiptByBarcode([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string barcode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), barcode);
			return ((ISingleResult<sp_getReceiptByBarcodeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_insertNewRecipt")]
		public int sp_insertNewRecipt([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string barcode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> itemnb, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> totaldollar, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> totallbp)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), barcode, itemnb, totaldollar, totallbp);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_insertNewReciptDetail")]
		public int sp_insertNewReciptDetail([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> rid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> qte, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> pricedollar, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> totaldollar, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pricelbp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> totallbp)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rid, pid, qte, pricedollar, totaldollar, pricelbp, totallbp);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_select_item")]
		public ISingleResult<sp_select_itemResult> sp_select_item([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string str)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), str);
			return ((ISingleResult<sp_select_itemResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UpdateItem")]
		public int sp_UpdateItem([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> qte, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string unit)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, name, qte, unit);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_deleteReceiptByBarcode")]
		public int sp_deleteReceiptByBarcode([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string barcode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), barcode);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_deleteReceiptDetailsByRID")]
		public int sp_deleteReceiptDetailsByRID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_selectReceipts")]
		public ISingleResult<sp_selectReceiptsResult> sp_selectReceipts([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string str)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), str);
			return ((ISingleResult<sp_selectReceiptsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_getReceiptByID")]
		public ISingleResult<sp_getReceiptByIDResult> sp_getReceiptByID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<sp_getReceiptByIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UpdateProductQuantity")]
		public int sp_UpdateProductQuantity([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> qte)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, qte);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UpdateProduct")]
		public int sp_UpdateProduct([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string barcode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> qte, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> price, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> hasQuantity, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, name, barcode, qte, price, hasQuantity, sid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_select_suppliers")]
		public ISingleResult<sp_select_suppliersResult> sp_select_suppliers([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string str)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), str);
			return ((ISingleResult<sp_select_suppliersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UpdateSupplier")]
		public int sp_UpdateSupplier([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, name, phone, email);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_enableSupplierByID")]
		public int sp_enableSupplierByID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_disableSupplierByID")]
		public int sp_disableSupplierByID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_addNewSupplier")]
		public int sp_addNewSupplier([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, phone, email);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_addNewProduct")]
		public int sp_addNewProduct([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string barcode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> qte, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> price, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> hasQuantity, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, barcode, qte, price, hasQuantity, sid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_getSIDBySNAME")]
		public ISingleResult<sp_getSIDBySNAMEResult> sp_getSIDBySNAME([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name);
			return ((ISingleResult<sp_getSIDBySNAMEResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_getSupplierByID")]
		public ISingleResult<sp_getSupplierByIDResult> sp_getSupplierByID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<sp_getSupplierByIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_select_products")]
		public ISingleResult<sp_select_productsResult> sp_select_products([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string str)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), str);
			return ((ISingleResult<sp_select_productsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_selectReceiptsDetails")]
		public ISingleResult<sp_selectReceiptsDetailsResult> sp_selectReceiptsDetails([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<sp_selectReceiptsDetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_getSupplierByNAME")]
		public ISingleResult<sp_getSupplierByNAMEResult> sp_getSupplierByNAME([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name);
			return ((ISingleResult<sp_getSupplierByNAMEResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_getProductByName")]
		public ISingleResult<sp_getProductByNameResult> sp_getProductByName([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name);
			return ((ISingleResult<sp_getProductByNameResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLITEMS")]
	public partial class TBLITEM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IID;
		
		private string _INAME;
		
		private System.Nullable<int> _QTE;
		
		private string _UNIT;
		
		private System.Nullable<System.DateTime> _ADD_DATE;
		
		private System.Nullable<bool> _ENABLED;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIIDChanging(int value);
    partial void OnIIDChanged();
    partial void OnINAMEChanging(string value);
    partial void OnINAMEChanged();
    partial void OnQTEChanging(System.Nullable<int> value);
    partial void OnQTEChanged();
    partial void OnUNITChanging(string value);
    partial void OnUNITChanged();
    partial void OnADD_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnADD_DATEChanged();
    partial void OnENABLEDChanging(System.Nullable<bool> value);
    partial void OnENABLEDChanged();
    #endregion
		
		public TBLITEM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IID
		{
			get
			{
				return this._IID;
			}
			set
			{
				if ((this._IID != value))
				{
					this.OnIIDChanging(value);
					this.SendPropertyChanging();
					this._IID = value;
					this.SendPropertyChanged("IID");
					this.OnIIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INAME", DbType="NVarChar(100)")]
		public string INAME
		{
			get
			{
				return this._INAME;
			}
			set
			{
				if ((this._INAME != value))
				{
					this.OnINAMEChanging(value);
					this.SendPropertyChanging();
					this._INAME = value;
					this.SendPropertyChanged("INAME");
					this.OnINAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTE", DbType="Int")]
		public System.Nullable<int> QTE
		{
			get
			{
				return this._QTE;
			}
			set
			{
				if ((this._QTE != value))
				{
					this.OnQTEChanging(value);
					this.SendPropertyChanging();
					this._QTE = value;
					this.SendPropertyChanged("QTE");
					this.OnQTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIT", DbType="NVarChar(20)")]
		public string UNIT
		{
			get
			{
				return this._UNIT;
			}
			set
			{
				if ((this._UNIT != value))
				{
					this.OnUNITChanging(value);
					this.SendPropertyChanging();
					this._UNIT = value;
					this.SendPropertyChanged("UNIT");
					this.OnUNITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADD_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> ADD_DATE
		{
			get
			{
				return this._ADD_DATE;
			}
			set
			{
				if ((this._ADD_DATE != value))
				{
					this.OnADD_DATEChanging(value);
					this.SendPropertyChanging();
					this._ADD_DATE = value;
					this.SendPropertyChanged("ADD_DATE");
					this.OnADD_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENABLED", DbType="Bit")]
		public System.Nullable<bool> ENABLED
		{
			get
			{
				return this._ENABLED;
			}
			set
			{
				if ((this._ENABLED != value))
				{
					this.OnENABLEDChanging(value);
					this.SendPropertyChanging();
					this._ENABLED = value;
					this.SendPropertyChanged("ENABLED");
					this.OnENABLEDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLRECEIPTS_DETAILS")]
	public partial class TBLRECEIPTS_DETAIL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _RID;
		
		private System.Nullable<int> _PID;
		
		private System.Nullable<int> _QTE;
		
		private System.Nullable<double> _PRICE;
		
		private System.Nullable<double> _TOTAL_PRICE;
		
		private EntityRef<TBLRECEIPT> _TBLRECEIPT;
		
		private EntityRef<TBLPRODUCT> _TBLPRODUCT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnRIDChanging(System.Nullable<int> value);
    partial void OnRIDChanged();
    partial void OnPIDChanging(System.Nullable<int> value);
    partial void OnPIDChanged();
    partial void OnQTEChanging(System.Nullable<int> value);
    partial void OnQTEChanged();
    partial void OnPRICEChanging(System.Nullable<double> value);
    partial void OnPRICEChanged();
    partial void OnTOTAL_PRICEChanging(System.Nullable<double> value);
    partial void OnTOTAL_PRICEChanged();
    #endregion
		
		public TBLRECEIPTS_DETAIL()
		{
			this._TBLRECEIPT = default(EntityRef<TBLRECEIPT>);
			this._TBLPRODUCT = default(EntityRef<TBLPRODUCT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RID", DbType="Int")]
		public System.Nullable<int> RID
		{
			get
			{
				return this._RID;
			}
			set
			{
				if ((this._RID != value))
				{
					if (this._TBLRECEIPT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRIDChanging(value);
					this.SendPropertyChanging();
					this._RID = value;
					this.SendPropertyChanged("RID");
					this.OnRIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PID", DbType="Int")]
		public System.Nullable<int> PID
		{
			get
			{
				return this._PID;
			}
			set
			{
				if ((this._PID != value))
				{
					if (this._TBLPRODUCT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPIDChanging(value);
					this.SendPropertyChanging();
					this._PID = value;
					this.SendPropertyChanged("PID");
					this.OnPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTE", DbType="Int")]
		public System.Nullable<int> QTE
		{
			get
			{
				return this._QTE;
			}
			set
			{
				if ((this._QTE != value))
				{
					this.OnQTEChanging(value);
					this.SendPropertyChanging();
					this._QTE = value;
					this.SendPropertyChanged("QTE");
					this.OnQTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRICE", DbType="Float")]
		public System.Nullable<double> PRICE
		{
			get
			{
				return this._PRICE;
			}
			set
			{
				if ((this._PRICE != value))
				{
					this.OnPRICEChanging(value);
					this.SendPropertyChanging();
					this._PRICE = value;
					this.SendPropertyChanged("PRICE");
					this.OnPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_PRICE", DbType="Float")]
		public System.Nullable<double> TOTAL_PRICE
		{
			get
			{
				return this._TOTAL_PRICE;
			}
			set
			{
				if ((this._TOTAL_PRICE != value))
				{
					this.OnTOTAL_PRICEChanging(value);
					this.SendPropertyChanging();
					this._TOTAL_PRICE = value;
					this.SendPropertyChanged("TOTAL_PRICE");
					this.OnTOTAL_PRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLRECEIPT_TBLRECEIPTS_DETAIL", Storage="_TBLRECEIPT", ThisKey="RID", OtherKey="RID", IsForeignKey=true)]
		public TBLRECEIPT TBLRECEIPT
		{
			get
			{
				return this._TBLRECEIPT.Entity;
			}
			set
			{
				TBLRECEIPT previousValue = this._TBLRECEIPT.Entity;
				if (((previousValue != value) 
							|| (this._TBLRECEIPT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBLRECEIPT.Entity = null;
						previousValue.TBLRECEIPTS_DETAILs.Remove(this);
					}
					this._TBLRECEIPT.Entity = value;
					if ((value != null))
					{
						value.TBLRECEIPTS_DETAILs.Add(this);
						this._RID = value.RID;
					}
					else
					{
						this._RID = default(Nullable<int>);
					}
					this.SendPropertyChanged("TBLRECEIPT");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLPRODUCT_TBLRECEIPTS_DETAIL", Storage="_TBLPRODUCT", ThisKey="PID", OtherKey="PID", IsForeignKey=true)]
		public TBLPRODUCT TBLPRODUCT
		{
			get
			{
				return this._TBLPRODUCT.Entity;
			}
			set
			{
				TBLPRODUCT previousValue = this._TBLPRODUCT.Entity;
				if (((previousValue != value) 
							|| (this._TBLPRODUCT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBLPRODUCT.Entity = null;
						previousValue.TBLRECEIPTS_DETAILs.Remove(this);
					}
					this._TBLPRODUCT.Entity = value;
					if ((value != null))
					{
						value.TBLRECEIPTS_DETAILs.Add(this);
						this._PID = value.PID;
					}
					else
					{
						this._PID = default(Nullable<int>);
					}
					this.SendPropertyChanged("TBLPRODUCT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLRECEIPTS")]
	public partial class TBLRECEIPT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RID;
		
		private System.Nullable<int> _RITEM_NB;
		
		private System.Nullable<double> _TOTAL_AMOUNTDollar;
		
		private System.Nullable<int> _TOTAL_AMOUNTLBP;
		
		private System.Nullable<System.DateTime> _RDATE;
		
		private string _RBARCODE;
		
		private EntitySet<TBLRECEIPTS_DETAIL> _TBLRECEIPTS_DETAILs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRIDChanging(int value);
    partial void OnRIDChanged();
    partial void OnRITEM_NBChanging(System.Nullable<int> value);
    partial void OnRITEM_NBChanged();
    partial void OnTOTAL_AMOUNTDollarChanging(System.Nullable<double> value);
    partial void OnTOTAL_AMOUNTDollarChanged();
    partial void OnTOTAL_AMOUNTLBPChanging(System.Nullable<int> value);
    partial void OnTOTAL_AMOUNTLBPChanged();
    partial void OnRDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnRDATEChanged();
    partial void OnRBARCODEChanging(string value);
    partial void OnRBARCODEChanged();
    #endregion
		
		public TBLRECEIPT()
		{
			this._TBLRECEIPTS_DETAILs = new EntitySet<TBLRECEIPTS_DETAIL>(new Action<TBLRECEIPTS_DETAIL>(this.attach_TBLRECEIPTS_DETAILs), new Action<TBLRECEIPTS_DETAIL>(this.detach_TBLRECEIPTS_DETAILs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RID
		{
			get
			{
				return this._RID;
			}
			set
			{
				if ((this._RID != value))
				{
					this.OnRIDChanging(value);
					this.SendPropertyChanging();
					this._RID = value;
					this.SendPropertyChanged("RID");
					this.OnRIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RITEM_NB", DbType="Int")]
		public System.Nullable<int> RITEM_NB
		{
			get
			{
				return this._RITEM_NB;
			}
			set
			{
				if ((this._RITEM_NB != value))
				{
					this.OnRITEM_NBChanging(value);
					this.SendPropertyChanging();
					this._RITEM_NB = value;
					this.SendPropertyChanged("RITEM_NB");
					this.OnRITEM_NBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_AMOUNTDollar", DbType="Float")]
		public System.Nullable<double> TOTAL_AMOUNTDollar
		{
			get
			{
				return this._TOTAL_AMOUNTDollar;
			}
			set
			{
				if ((this._TOTAL_AMOUNTDollar != value))
				{
					this.OnTOTAL_AMOUNTDollarChanging(value);
					this.SendPropertyChanging();
					this._TOTAL_AMOUNTDollar = value;
					this.SendPropertyChanged("TOTAL_AMOUNTDollar");
					this.OnTOTAL_AMOUNTDollarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_AMOUNTLBP", DbType="Int")]
		public System.Nullable<int> TOTAL_AMOUNTLBP
		{
			get
			{
				return this._TOTAL_AMOUNTLBP;
			}
			set
			{
				if ((this._TOTAL_AMOUNTLBP != value))
				{
					this.OnTOTAL_AMOUNTLBPChanging(value);
					this.SendPropertyChanging();
					this._TOTAL_AMOUNTLBP = value;
					this.SendPropertyChanged("TOTAL_AMOUNTLBP");
					this.OnTOTAL_AMOUNTLBPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> RDATE
		{
			get
			{
				return this._RDATE;
			}
			set
			{
				if ((this._RDATE != value))
				{
					this.OnRDATEChanging(value);
					this.SendPropertyChanging();
					this._RDATE = value;
					this.SendPropertyChanged("RDATE");
					this.OnRDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RBARCODE", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string RBARCODE
		{
			get
			{
				return this._RBARCODE;
			}
			set
			{
				if ((this._RBARCODE != value))
				{
					this.OnRBARCODEChanging(value);
					this.SendPropertyChanging();
					this._RBARCODE = value;
					this.SendPropertyChanged("RBARCODE");
					this.OnRBARCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLRECEIPT_TBLRECEIPTS_DETAIL", Storage="_TBLRECEIPTS_DETAILs", ThisKey="RID", OtherKey="RID")]
		public EntitySet<TBLRECEIPTS_DETAIL> TBLRECEIPTS_DETAILs
		{
			get
			{
				return this._TBLRECEIPTS_DETAILs;
			}
			set
			{
				this._TBLRECEIPTS_DETAILs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBLRECEIPTS_DETAILs(TBLRECEIPTS_DETAIL entity)
		{
			this.SendPropertyChanging();
			entity.TBLRECEIPT = this;
		}
		
		private void detach_TBLRECEIPTS_DETAILs(TBLRECEIPTS_DETAIL entity)
		{
			this.SendPropertyChanging();
			entity.TBLRECEIPT = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLSUPPLIERS")]
	public partial class TBLSUPPLIER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SID;
		
		private string _SNAME;
		
		private string _SPHONE;
		
		private string _SEMAIL;
		
		private System.Nullable<System.DateTime> _ADD_DATE;
		
		private System.Nullable<bool> _ENABLED;
		
		private EntitySet<TBLPRODUCT> _TBLPRODUCTs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSIDChanging(int value);
    partial void OnSIDChanged();
    partial void OnSNAMEChanging(string value);
    partial void OnSNAMEChanged();
    partial void OnSPHONEChanging(string value);
    partial void OnSPHONEChanged();
    partial void OnSEMAILChanging(string value);
    partial void OnSEMAILChanged();
    partial void OnADD_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnADD_DATEChanged();
    partial void OnENABLEDChanging(System.Nullable<bool> value);
    partial void OnENABLEDChanged();
    #endregion
		
		public TBLSUPPLIER()
		{
			this._TBLPRODUCTs = new EntitySet<TBLPRODUCT>(new Action<TBLPRODUCT>(this.attach_TBLPRODUCTs), new Action<TBLPRODUCT>(this.detach_TBLPRODUCTs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SID
		{
			get
			{
				return this._SID;
			}
			set
			{
				if ((this._SID != value))
				{
					this.OnSIDChanging(value);
					this.SendPropertyChanging();
					this._SID = value;
					this.SendPropertyChanged("SID");
					this.OnSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SNAME", DbType="NVarChar(50)")]
		public string SNAME
		{
			get
			{
				return this._SNAME;
			}
			set
			{
				if ((this._SNAME != value))
				{
					this.OnSNAMEChanging(value);
					this.SendPropertyChanging();
					this._SNAME = value;
					this.SendPropertyChanged("SNAME");
					this.OnSNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPHONE", DbType="NVarChar(50)")]
		public string SPHONE
		{
			get
			{
				return this._SPHONE;
			}
			set
			{
				if ((this._SPHONE != value))
				{
					this.OnSPHONEChanging(value);
					this.SendPropertyChanging();
					this._SPHONE = value;
					this.SendPropertyChanged("SPHONE");
					this.OnSPHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEMAIL", DbType="NVarChar(50)")]
		public string SEMAIL
		{
			get
			{
				return this._SEMAIL;
			}
			set
			{
				if ((this._SEMAIL != value))
				{
					this.OnSEMAILChanging(value);
					this.SendPropertyChanging();
					this._SEMAIL = value;
					this.SendPropertyChanged("SEMAIL");
					this.OnSEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADD_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> ADD_DATE
		{
			get
			{
				return this._ADD_DATE;
			}
			set
			{
				if ((this._ADD_DATE != value))
				{
					this.OnADD_DATEChanging(value);
					this.SendPropertyChanging();
					this._ADD_DATE = value;
					this.SendPropertyChanged("ADD_DATE");
					this.OnADD_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENABLED", DbType="Bit")]
		public System.Nullable<bool> ENABLED
		{
			get
			{
				return this._ENABLED;
			}
			set
			{
				if ((this._ENABLED != value))
				{
					this.OnENABLEDChanging(value);
					this.SendPropertyChanging();
					this._ENABLED = value;
					this.SendPropertyChanged("ENABLED");
					this.OnENABLEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLSUPPLIER_TBLPRODUCT", Storage="_TBLPRODUCTs", ThisKey="SID", OtherKey="SID")]
		public EntitySet<TBLPRODUCT> TBLPRODUCTs
		{
			get
			{
				return this._TBLPRODUCTs;
			}
			set
			{
				this._TBLPRODUCTs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBLPRODUCTs(TBLPRODUCT entity)
		{
			this.SendPropertyChanging();
			entity.TBLSUPPLIER = this;
		}
		
		private void detach_TBLPRODUCTs(TBLPRODUCT entity)
		{
			this.SendPropertyChanging();
			entity.TBLSUPPLIER = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLPRODUCTS")]
	public partial class TBLPRODUCT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PID;
		
		private string _PNAME;
		
		private System.Nullable<int> _QTE;
		
		private System.Nullable<double> _PRICE;
		
		private System.Nullable<System.DateTime> _ADD_DATE;
		
		private System.Nullable<bool> _ENABLED;
		
		private System.Nullable<bool> _HasQuantity;
		
		private string _BARCODE;
		
		private System.Nullable<int> _SID;
		
		private EntitySet<TBLRECEIPTS_DETAIL> _TBLRECEIPTS_DETAILs;
		
		private EntityRef<TBLSUPPLIER> _TBLSUPPLIER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPIDChanging(int value);
    partial void OnPIDChanged();
    partial void OnPNAMEChanging(string value);
    partial void OnPNAMEChanged();
    partial void OnQTEChanging(System.Nullable<int> value);
    partial void OnQTEChanged();
    partial void OnPRICEChanging(System.Nullable<double> value);
    partial void OnPRICEChanged();
    partial void OnADD_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnADD_DATEChanged();
    partial void OnENABLEDChanging(System.Nullable<bool> value);
    partial void OnENABLEDChanged();
    partial void OnHasQuantityChanging(System.Nullable<bool> value);
    partial void OnHasQuantityChanged();
    partial void OnBARCODEChanging(string value);
    partial void OnBARCODEChanged();
    partial void OnSIDChanging(System.Nullable<int> value);
    partial void OnSIDChanged();
    #endregion
		
		public TBLPRODUCT()
		{
			this._TBLRECEIPTS_DETAILs = new EntitySet<TBLRECEIPTS_DETAIL>(new Action<TBLRECEIPTS_DETAIL>(this.attach_TBLRECEIPTS_DETAILs), new Action<TBLRECEIPTS_DETAIL>(this.detach_TBLRECEIPTS_DETAILs));
			this._TBLSUPPLIER = default(EntityRef<TBLSUPPLIER>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PID
		{
			get
			{
				return this._PID;
			}
			set
			{
				if ((this._PID != value))
				{
					this.OnPIDChanging(value);
					this.SendPropertyChanging();
					this._PID = value;
					this.SendPropertyChanged("PID");
					this.OnPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PNAME", DbType="NVarChar(100)")]
		public string PNAME
		{
			get
			{
				return this._PNAME;
			}
			set
			{
				if ((this._PNAME != value))
				{
					this.OnPNAMEChanging(value);
					this.SendPropertyChanging();
					this._PNAME = value;
					this.SendPropertyChanged("PNAME");
					this.OnPNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTE", DbType="Int")]
		public System.Nullable<int> QTE
		{
			get
			{
				return this._QTE;
			}
			set
			{
				if ((this._QTE != value))
				{
					this.OnQTEChanging(value);
					this.SendPropertyChanging();
					this._QTE = value;
					this.SendPropertyChanged("QTE");
					this.OnQTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRICE", DbType="Float")]
		public System.Nullable<double> PRICE
		{
			get
			{
				return this._PRICE;
			}
			set
			{
				if ((this._PRICE != value))
				{
					this.OnPRICEChanging(value);
					this.SendPropertyChanging();
					this._PRICE = value;
					this.SendPropertyChanged("PRICE");
					this.OnPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADD_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> ADD_DATE
		{
			get
			{
				return this._ADD_DATE;
			}
			set
			{
				if ((this._ADD_DATE != value))
				{
					this.OnADD_DATEChanging(value);
					this.SendPropertyChanging();
					this._ADD_DATE = value;
					this.SendPropertyChanged("ADD_DATE");
					this.OnADD_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENABLED", DbType="Bit")]
		public System.Nullable<bool> ENABLED
		{
			get
			{
				return this._ENABLED;
			}
			set
			{
				if ((this._ENABLED != value))
				{
					this.OnENABLEDChanging(value);
					this.SendPropertyChanging();
					this._ENABLED = value;
					this.SendPropertyChanged("ENABLED");
					this.OnENABLEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasQuantity", DbType="Bit")]
		public System.Nullable<bool> HasQuantity
		{
			get
			{
				return this._HasQuantity;
			}
			set
			{
				if ((this._HasQuantity != value))
				{
					this.OnHasQuantityChanging(value);
					this.SendPropertyChanging();
					this._HasQuantity = value;
					this.SendPropertyChanged("HasQuantity");
					this.OnHasQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BARCODE", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string BARCODE
		{
			get
			{
				return this._BARCODE;
			}
			set
			{
				if ((this._BARCODE != value))
				{
					this.OnBARCODEChanging(value);
					this.SendPropertyChanging();
					this._BARCODE = value;
					this.SendPropertyChanged("BARCODE");
					this.OnBARCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", DbType="Int")]
		public System.Nullable<int> SID
		{
			get
			{
				return this._SID;
			}
			set
			{
				if ((this._SID != value))
				{
					if (this._TBLSUPPLIER.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSIDChanging(value);
					this.SendPropertyChanging();
					this._SID = value;
					this.SendPropertyChanged("SID");
					this.OnSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLPRODUCT_TBLRECEIPTS_DETAIL", Storage="_TBLRECEIPTS_DETAILs", ThisKey="PID", OtherKey="PID")]
		public EntitySet<TBLRECEIPTS_DETAIL> TBLRECEIPTS_DETAILs
		{
			get
			{
				return this._TBLRECEIPTS_DETAILs;
			}
			set
			{
				this._TBLRECEIPTS_DETAILs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLSUPPLIER_TBLPRODUCT", Storage="_TBLSUPPLIER", ThisKey="SID", OtherKey="SID", IsForeignKey=true)]
		public TBLSUPPLIER TBLSUPPLIER
		{
			get
			{
				return this._TBLSUPPLIER.Entity;
			}
			set
			{
				TBLSUPPLIER previousValue = this._TBLSUPPLIER.Entity;
				if (((previousValue != value) 
							|| (this._TBLSUPPLIER.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBLSUPPLIER.Entity = null;
						previousValue.TBLPRODUCTs.Remove(this);
					}
					this._TBLSUPPLIER.Entity = value;
					if ((value != null))
					{
						value.TBLPRODUCTs.Add(this);
						this._SID = value.SID;
					}
					else
					{
						this._SID = default(Nullable<int>);
					}
					this.SendPropertyChanged("TBLSUPPLIER");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBLRECEIPTS_DETAILs(TBLRECEIPTS_DETAIL entity)
		{
			this.SendPropertyChanging();
			entity.TBLPRODUCT = this;
		}
		
		private void detach_TBLRECEIPTS_DETAILs(TBLRECEIPTS_DETAIL entity)
		{
			this.SendPropertyChanging();
			entity.TBLPRODUCT = null;
		}
	}
	
	public partial class sp_getLastReceiptIDResult
	{
		
		private System.Nullable<int> _MAX_RID;
		
		public sp_getLastReceiptIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAX_RID", DbType="Int")]
		public System.Nullable<int> MAX_RID
		{
			get
			{
				return this._MAX_RID;
			}
			set
			{
				if ((this._MAX_RID != value))
				{
					this._MAX_RID = value;
				}
			}
		}
	}
	
	public partial class sp_getProductsCountResult
	{
		
		private System.Nullable<int> _Product_Number;
		
		public sp_getProductsCountResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_Number", DbType="Int")]
		public System.Nullable<int> Product_Number
		{
			get
			{
				return this._Product_Number;
			}
			set
			{
				if ((this._Product_Number != value))
				{
					this._Product_Number = value;
				}
			}
		}
	}
	
	public partial class sp_getReceiptByBarcodeResult
	{
		
		private int _RID;
		
		private System.Nullable<int> _RITEM_NB;
		
		private System.Nullable<double> _TOTAL_AMOUNTDollar;
		
		private System.Nullable<int> _TOTAL_AMOUNTLBP;
		
		private System.Nullable<System.DateTime> _RDATE;
		
		private string _RBARCODE;
		
		public sp_getReceiptByBarcodeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RID", DbType="Int NOT NULL")]
		public int RID
		{
			get
			{
				return this._RID;
			}
			set
			{
				if ((this._RID != value))
				{
					this._RID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RITEM_NB", DbType="Int")]
		public System.Nullable<int> RITEM_NB
		{
			get
			{
				return this._RITEM_NB;
			}
			set
			{
				if ((this._RITEM_NB != value))
				{
					this._RITEM_NB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_AMOUNTDollar", DbType="Float")]
		public System.Nullable<double> TOTAL_AMOUNTDollar
		{
			get
			{
				return this._TOTAL_AMOUNTDollar;
			}
			set
			{
				if ((this._TOTAL_AMOUNTDollar != value))
				{
					this._TOTAL_AMOUNTDollar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_AMOUNTLBP", DbType="Int")]
		public System.Nullable<int> TOTAL_AMOUNTLBP
		{
			get
			{
				return this._TOTAL_AMOUNTLBP;
			}
			set
			{
				if ((this._TOTAL_AMOUNTLBP != value))
				{
					this._TOTAL_AMOUNTLBP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> RDATE
		{
			get
			{
				return this._RDATE;
			}
			set
			{
				if ((this._RDATE != value))
				{
					this._RDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RBARCODE", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string RBARCODE
		{
			get
			{
				return this._RBARCODE;
			}
			set
			{
				if ((this._RBARCODE != value))
				{
					this._RBARCODE = value;
				}
			}
		}
	}
	
	public partial class sp_select_itemResult
	{
		
		private int _ID;
		
		private string _ItemName;
		
		private System.Nullable<int> _Quantity;
		
		private string _Unit;
		
		private System.Nullable<System.DateTime> _AddedDate;
		
		private string _Status;
		
		public sp_select_itemResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemName", DbType="NVarChar(100)")]
		public string ItemName
		{
			get
			{
				return this._ItemName;
			}
			set
			{
				if ((this._ItemName != value))
				{
					this._ItemName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int")]
		public System.Nullable<int> Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit", DbType="NVarChar(20)")]
		public string Unit
		{
			get
			{
				return this._Unit;
			}
			set
			{
				if ((this._Unit != value))
				{
					this._Unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> AddedDate
		{
			get
			{
				return this._AddedDate;
			}
			set
			{
				if ((this._AddedDate != value))
				{
					this._AddedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
	
	public partial class sp_selectReceiptsResult
	{
		
		private int _ID;
		
		private string _BARCODE;
		
		private System.Nullable<int> _NumberOfItem;
		
		private System.Nullable<double> _TotalDolarPrice;
		
		private System.Nullable<int> _TotalLBPPrice;
		
		private System.Nullable<System.DateTime> _Date;
		
		public sp_selectReceiptsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BARCODE", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string BARCODE
		{
			get
			{
				return this._BARCODE;
			}
			set
			{
				if ((this._BARCODE != value))
				{
					this._BARCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberOfItem", DbType="Int")]
		public System.Nullable<int> NumberOfItem
		{
			get
			{
				return this._NumberOfItem;
			}
			set
			{
				if ((this._NumberOfItem != value))
				{
					this._NumberOfItem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalDolarPrice", DbType="Float")]
		public System.Nullable<double> TotalDolarPrice
		{
			get
			{
				return this._TotalDolarPrice;
			}
			set
			{
				if ((this._TotalDolarPrice != value))
				{
					this._TotalDolarPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalLBPPrice", DbType="Int")]
		public System.Nullable<int> TotalLBPPrice
		{
			get
			{
				return this._TotalLBPPrice;
			}
			set
			{
				if ((this._TotalLBPPrice != value))
				{
					this._TotalLBPPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
	}
	
	public partial class sp_getReceiptByIDResult
	{
		
		private int _RID;
		
		private System.Nullable<int> _RITEM_NB;
		
		private System.Nullable<double> _TOTAL_AMOUNTDollar;
		
		private System.Nullable<int> _TOTAL_AMOUNTLBP;
		
		private System.Nullable<System.DateTime> _RDATE;
		
		private string _RBARCODE;
		
		public sp_getReceiptByIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RID", DbType="Int NOT NULL")]
		public int RID
		{
			get
			{
				return this._RID;
			}
			set
			{
				if ((this._RID != value))
				{
					this._RID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RITEM_NB", DbType="Int")]
		public System.Nullable<int> RITEM_NB
		{
			get
			{
				return this._RITEM_NB;
			}
			set
			{
				if ((this._RITEM_NB != value))
				{
					this._RITEM_NB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_AMOUNTDollar", DbType="Float")]
		public System.Nullable<double> TOTAL_AMOUNTDollar
		{
			get
			{
				return this._TOTAL_AMOUNTDollar;
			}
			set
			{
				if ((this._TOTAL_AMOUNTDollar != value))
				{
					this._TOTAL_AMOUNTDollar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_AMOUNTLBP", DbType="Int")]
		public System.Nullable<int> TOTAL_AMOUNTLBP
		{
			get
			{
				return this._TOTAL_AMOUNTLBP;
			}
			set
			{
				if ((this._TOTAL_AMOUNTLBP != value))
				{
					this._TOTAL_AMOUNTLBP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> RDATE
		{
			get
			{
				return this._RDATE;
			}
			set
			{
				if ((this._RDATE != value))
				{
					this._RDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RBARCODE", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string RBARCODE
		{
			get
			{
				return this._RBARCODE;
			}
			set
			{
				if ((this._RBARCODE != value))
				{
					this._RBARCODE = value;
				}
			}
		}
	}
	
	public partial class sp_select_suppliersResult
	{
		
		private int _ID;
		
		private string _SupplierName;
		
		private string _PhoneNumber;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _AddedDate;
		
		private string _Status;
		
		public sp_select_suppliersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierName", DbType="NVarChar(50)")]
		public string SupplierName
		{
			get
			{
				return this._SupplierName;
			}
			set
			{
				if ((this._SupplierName != value))
				{
					this._SupplierName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="NVarChar(50)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this._PhoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddedDate", DbType="Date")]
		public System.Nullable<System.DateTime> AddedDate
		{
			get
			{
				return this._AddedDate;
			}
			set
			{
				if ((this._AddedDate != value))
				{
					this._AddedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
	
	public partial class sp_getSIDBySNAMEResult
	{
		
		private int _SID;
		
		public sp_getSIDBySNAMEResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", DbType="Int NOT NULL")]
		public int SID
		{
			get
			{
				return this._SID;
			}
			set
			{
				if ((this._SID != value))
				{
					this._SID = value;
				}
			}
		}
	}
	
	public partial class sp_getSupplierByIDResult
	{
		
		private int _SID;
		
		private string _SNAME;
		
		private string _SPHONE;
		
		private string _SEMAIL;
		
		private System.Nullable<System.DateTime> _ADD_DATE;
		
		private System.Nullable<bool> _ENABLED;
		
		public sp_getSupplierByIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", DbType="Int NOT NULL")]
		public int SID
		{
			get
			{
				return this._SID;
			}
			set
			{
				if ((this._SID != value))
				{
					this._SID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SNAME", DbType="NVarChar(50)")]
		public string SNAME
		{
			get
			{
				return this._SNAME;
			}
			set
			{
				if ((this._SNAME != value))
				{
					this._SNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPHONE", DbType="NVarChar(50)")]
		public string SPHONE
		{
			get
			{
				return this._SPHONE;
			}
			set
			{
				if ((this._SPHONE != value))
				{
					this._SPHONE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEMAIL", DbType="NVarChar(50)")]
		public string SEMAIL
		{
			get
			{
				return this._SEMAIL;
			}
			set
			{
				if ((this._SEMAIL != value))
				{
					this._SEMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADD_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> ADD_DATE
		{
			get
			{
				return this._ADD_DATE;
			}
			set
			{
				if ((this._ADD_DATE != value))
				{
					this._ADD_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENABLED", DbType="Bit")]
		public System.Nullable<bool> ENABLED
		{
			get
			{
				return this._ENABLED;
			}
			set
			{
				if ((this._ENABLED != value))
				{
					this._ENABLED = value;
				}
			}
		}
	}
	
	public partial class sp_select_productsResult
	{
		
		private int _ID;
		
		private string _Barcode;
		
		private string _ProductName;
		
		private string _SupplierName;
		
		private System.Nullable<int> _Quantity;
		
		private System.Nullable<double> _Price;
		
		private System.Nullable<System.DateTime> _AddedDate;
		
		private string _Status;
		
		public sp_select_productsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barcode", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Barcode
		{
			get
			{
				return this._Barcode;
			}
			set
			{
				if ((this._Barcode != value))
				{
					this._Barcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="NVarChar(100)")]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this._ProductName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierName", DbType="NVarChar(50)")]
		public string SupplierName
		{
			get
			{
				return this._SupplierName;
			}
			set
			{
				if ((this._SupplierName != value))
				{
					this._SupplierName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int")]
		public System.Nullable<int> Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Float")]
		public System.Nullable<double> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> AddedDate
		{
			get
			{
				return this._AddedDate;
			}
			set
			{
				if ((this._AddedDate != value))
				{
					this._AddedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
	
	public partial class sp_selectReceiptsDetailsResult
	{
		
		private string _Barcode;
		
		private System.Nullable<int> _RID;
		
		private string _ProductName;
		
		private string _SupplierName;
		
		private System.Nullable<int> _Quantity;
		
		private System.Nullable<double> _DollarPrice;
		
		private System.Nullable<int> _LBPPrice;
		
		private System.Nullable<double> _TotalDolarPrice;
		
		private System.Nullable<int> _TotalLBPPrice;
		
		public sp_selectReceiptsDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barcode", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Barcode
		{
			get
			{
				return this._Barcode;
			}
			set
			{
				if ((this._Barcode != value))
				{
					this._Barcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RID", DbType="Int")]
		public System.Nullable<int> RID
		{
			get
			{
				return this._RID;
			}
			set
			{
				if ((this._RID != value))
				{
					this._RID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="NVarChar(100)")]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this._ProductName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierName", DbType="NVarChar(50)")]
		public string SupplierName
		{
			get
			{
				return this._SupplierName;
			}
			set
			{
				if ((this._SupplierName != value))
				{
					this._SupplierName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int")]
		public System.Nullable<int> Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DollarPrice", DbType="Float")]
		public System.Nullable<double> DollarPrice
		{
			get
			{
				return this._DollarPrice;
			}
			set
			{
				if ((this._DollarPrice != value))
				{
					this._DollarPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LBPPrice", DbType="Int")]
		public System.Nullable<int> LBPPrice
		{
			get
			{
				return this._LBPPrice;
			}
			set
			{
				if ((this._LBPPrice != value))
				{
					this._LBPPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalDolarPrice", DbType="Float")]
		public System.Nullable<double> TotalDolarPrice
		{
			get
			{
				return this._TotalDolarPrice;
			}
			set
			{
				if ((this._TotalDolarPrice != value))
				{
					this._TotalDolarPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalLBPPrice", DbType="Int")]
		public System.Nullable<int> TotalLBPPrice
		{
			get
			{
				return this._TotalLBPPrice;
			}
			set
			{
				if ((this._TotalLBPPrice != value))
				{
					this._TotalLBPPrice = value;
				}
			}
		}
	}
	
	public partial class sp_getSupplierByNAMEResult
	{
		
		private int _SID;
		
		private string _SNAME;
		
		private string _SPHONE;
		
		private string _SEMAIL;
		
		private System.Nullable<System.DateTime> _ADD_DATE;
		
		private System.Nullable<bool> _ENABLED;
		
		public sp_getSupplierByNAMEResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", DbType="Int NOT NULL")]
		public int SID
		{
			get
			{
				return this._SID;
			}
			set
			{
				if ((this._SID != value))
				{
					this._SID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SNAME", DbType="NVarChar(50)")]
		public string SNAME
		{
			get
			{
				return this._SNAME;
			}
			set
			{
				if ((this._SNAME != value))
				{
					this._SNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPHONE", DbType="NVarChar(50)")]
		public string SPHONE
		{
			get
			{
				return this._SPHONE;
			}
			set
			{
				if ((this._SPHONE != value))
				{
					this._SPHONE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEMAIL", DbType="NVarChar(50)")]
		public string SEMAIL
		{
			get
			{
				return this._SEMAIL;
			}
			set
			{
				if ((this._SEMAIL != value))
				{
					this._SEMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADD_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> ADD_DATE
		{
			get
			{
				return this._ADD_DATE;
			}
			set
			{
				if ((this._ADD_DATE != value))
				{
					this._ADD_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENABLED", DbType="Bit")]
		public System.Nullable<bool> ENABLED
		{
			get
			{
				return this._ENABLED;
			}
			set
			{
				if ((this._ENABLED != value))
				{
					this._ENABLED = value;
				}
			}
		}
	}
	
	public partial class sp_getProductByNameResult
	{
		
		private int _PID;
		
		private string _PNAME;
		
		private System.Nullable<int> _QTE;
		
		private System.Nullable<double> _PRICE;
		
		private System.Nullable<System.DateTime> _ADD_DATE;
		
		private System.Nullable<bool> _ENABLED;
		
		private System.Nullable<bool> _HasQuantity;
		
		private string _BARCODE;
		
		private System.Nullable<int> _SID;
		
		public sp_getProductByNameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PID", DbType="Int NOT NULL")]
		public int PID
		{
			get
			{
				return this._PID;
			}
			set
			{
				if ((this._PID != value))
				{
					this._PID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PNAME", DbType="NVarChar(100)")]
		public string PNAME
		{
			get
			{
				return this._PNAME;
			}
			set
			{
				if ((this._PNAME != value))
				{
					this._PNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTE", DbType="Int")]
		public System.Nullable<int> QTE
		{
			get
			{
				return this._QTE;
			}
			set
			{
				if ((this._QTE != value))
				{
					this._QTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRICE", DbType="Float")]
		public System.Nullable<double> PRICE
		{
			get
			{
				return this._PRICE;
			}
			set
			{
				if ((this._PRICE != value))
				{
					this._PRICE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADD_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> ADD_DATE
		{
			get
			{
				return this._ADD_DATE;
			}
			set
			{
				if ((this._ADD_DATE != value))
				{
					this._ADD_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENABLED", DbType="Bit")]
		public System.Nullable<bool> ENABLED
		{
			get
			{
				return this._ENABLED;
			}
			set
			{
				if ((this._ENABLED != value))
				{
					this._ENABLED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasQuantity", DbType="Bit")]
		public System.Nullable<bool> HasQuantity
		{
			get
			{
				return this._HasQuantity;
			}
			set
			{
				if ((this._HasQuantity != value))
				{
					this._HasQuantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BARCODE", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string BARCODE
		{
			get
			{
				return this._BARCODE;
			}
			set
			{
				if ((this._BARCODE != value))
				{
					this._BARCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", DbType="Int")]
		public System.Nullable<int> SID
		{
			get
			{
				return this._SID;
			}
			set
			{
				if ((this._SID != value))
				{
					this._SID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
