<?xml version="1.0" encoding="utf-8"?><Database Name="OrganigramSecurity" Class="OrganigramDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=sql\sql2008;Initial Catalog=OrganigramSecurity;Integrated Security=True" SettingsObjectName="MiniGram.Properties.Settings" SettingsPropertyName="OrganigramSecurityConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TblUsers" Member="TblUsers">
    <Type Name="TblUser">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BatchNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FullNameAr" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FullNameEn" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateOfEmployment" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="PIN" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="CardNumber" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="LastSeen" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ComputerName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="OldSmartID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PIN2" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="BatchNumber2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BloodGroup" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CardLableName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CardQR1" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CardQR2" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="OldBatchNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhoneNbr" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="qr1" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="qr2" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Sex" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FP" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FPindex" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Fpflag" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="idsPID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="isKafil" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="isDamanEnsured" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="isSubscribedToMedicalServices" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="kafalaLimit" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="dependentsStr" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="medicalServicesPeopleStr" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="isSubscribedToWifiService" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>